version: '3.4'

services:
  crud-oracle-mvc:
    image: crud-oracle-mvc
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3555:3555
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
